services:
  # Web Service
  - type: web
    name: horilla
    runtime: python
    plan: starter
    buildCommand: "./build.sh"
    startCommand: "gunicorn horilla.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: horilla-db
          property: connectionString
      - key: ALLOWED_HOSTS
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
      - key: TIME_ZONE
        value: UTC

databases:
  # PostgreSQL Database
  - name: horilla-db
    databaseName: horilla
    user: horilla
    plan: starter
